[package]
name = "reimburser"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
chrono = { version = "0.4.41", features = ["serde"] }
clap = { version = "4.5.45", features = ["derive"] }
pdfium-render = {version = "0.8.35"}
prettytable = "0.10.0"
regex = "1.11.1"

