use chrono::NaiveDate;

#[derive(Clone, Debug)]
pub enum Provider {
    NS,
    GVB,
}

#[derive(Clone, Debug)]
pub struct Trip {
    pub date: NaiveDate,
    pub provider: Provider, //NS or GVB
    pub from: String,
    pub to: String,
    pub price: f32,
}

impl Trip {
    pub fn new(date: NaiveDate, provider: Provider, from: String, to: String, price: f32) -> Trip {
        Trip {
            date,
            provider,
            from,
            to,
            price,
        }
    }
}

pub const ALL_NS_STATIONS: [&str; 399] = [
    "Aalten",
    "Abcoude",
    "Akkrum",
    "Alkmaar Noord",
    "Alkmaar",
    "Almelo de Riet",
    "Almelo",
    "Almere Buiten",
    "Almere Centrum",
    "Almere Muziekwijk",
    "Almere Oostvaarders",
    "Almere Parkwijk",
    "Almere Poort",
    "Alphen aan den Rijn",
    "Amersfoort Centraal",
    "Amersfoort Schothorst",
    "Amersfoort Vathorst",
    "Amsterdam Amstel",
    "Amsterdam Arena",
    "Amsterdam Bijlmer ArenA",
    "Amsterdam Centraal",
    "Amsterdam Holendrecht",
    "Amsterdam Lelylaan",
    "Amsterdam Muiderpoort",
    "Amsterdam RAI",
    "Amsterdam Science Park",
    "Amsterdam Sloterdijk",
    "Amsterdam Zuid",
    "Anna Paulowna",
    "Apeldoorn De Maten",
    "Apeldoorn Osseveld",
    "Apeldoorn",
    "Appingedam",
    "Arkel",
    "Arnemuiden",
    "Arnhem Presikhaaf",
    "Arnhem Centraal",
    "Arnhem Velperpoort",
    "Arnhem Zuid",
    "Assen",
    "Baarn",
    "Bad Nieuweschans",
    "Baflo",
    "Barendrecht",
    "Barneveld Centrum",
    "Barneveld Noord",
    "Barneveld Zuid",
    "Bedum",
    "Beek-Elsloo",
    "Beesd",
    "Beilen",
    "Bergen op Zoom",
    "Best",
    "Beverwijk",
    "Bilthoven",
    "Blerick",
    "Bloemendaal",
    "Bodegraven",
    "Borne",
    "Boskoop",
    "Boskoop Snijdelwijk",
    "Bovenkarspel Flora",
    "Bovenkarspel-Grootebroek",
    "Boven Hardinxveld",
    "Boxmeer",
    "Boxtel",
    "Breda Prinsenbeek",
    "Breda",
    "Breukelen",
    "Brummen",
    "Buitenpost",
    "Bunde",
    "Bunnik",
    "Bussum Zuid",
    "Capelle Schollevaar",
    "Castricum",
    "Chevremont",
    "Coevorden",
    "Cuijk",
    "Culemborg",
    "Daarlerveen",
    "Dalen",
    "Dalfsen",
    "De Vink",
    "De Westereen",
    "Deinum",
    "Delden",
    "Delft",
    "Delft Campus",
    "Delfzijl",
    "Delfzijl West",
    "Den Dolder",
    "Den Haag Centraal",
    "Den Haag Hollands Spoor",
    "Den Haag Laan van NOI",
    "Den Haag Mariahoeve",
    "Den Haag Moerwijk",
    "Den Haag Ypenburg",
    "Den Helder",
    "Den Helder Zuid",
    "Deurne",
    "Deventer Colmschate",
    "Deventer",
    "Didam",
    "Diemen",
    "Diemen Zuid",
    "Dieren",
    "Doetinchem De Huet",
    "Doetinchem",
    "Dordrecht",
    "Dordrecht Stadspolders",
    "Dordrecht Zuid",
    "Driebergen-Zeist",
    "Driehuis",
    "Dronryp",
    "Dronten",
    "Duiven",
    "Duivendrecht",
    "Echt",
    "Ede Centrum",
    "Ede-Wageningen",
    "Eemshaven",
    "Eijsden",
    "Eindhoven Centraal",
    "Eindhoven Stadion",
    "Eindhoven Strijp-S",
    "Elst",
    "Emmen",
    "Emmen Zuid",
    "Enkhuizen",
    "Enschede De Eschmarke",
    "Enschede Kennispark",
    "Enschede",
    "Ermelo",
    "Etten-Leur",
    "Eygelshoven Markt",
    "Eygelshoven",
    "Feanwâlden",
    "Franeker",
    "Gaanderen",
    "Geldermalsen",
    "Geldrop",
    "Geleen Oost",
    "Geleen-Lutterade",
    "Gilze-Rijen",
    "Glanerbrug",
    "Goes",
    "Goor",
    "Gorinchem",
    "Gouda Goverwelle",
    "Gouda",
    "Gramsbergen",
    "Grijpskerk",
    "Groningen Europapark",
    "Groningen Noord",
    "Groningen",
    "Grou-Jirnsum",
    "Haarlem",
    "Haarlem Spaarnwoude",
    "Halfweg-Zwanenburg",
    "Hardenberg",
    "Harderwijk",
    "Hardinxveld Blauwe Zoom",
    "Hardinxveld-Giessendam",
    "Haren (NL)",
    "Harlingen Haven",
    "Harlingen",
    "Heemskerk",
    "Heemstede-Aerdenhout",
    "Heerenveen IJsstadion (defunct 2015)",
    "Heerenveen",
    "Heerhugowaard",
    "Heerlen",
    "Heerlen Woonboulevard",
    "Heeze",
    "Heiloo",
    "Heino",
    "Helmond Brandevoort",
    "Helmond Brouwhuis",
    "Helmond",
    "Helmond 't Hout",
    "Hemmen-Dodewaard",
    "Hengelo Gezondheidspark",
    "Hengelo Oost",
    "Hengelo",
    "Hillegom",
    "Hilversum Media Park",
    "Hilversum",
    "Hilversum Sportpark",
    "Hindeloopen",
    "Hoensbroek",
    "Hoevelaken",
    "Hollandsche Rading",
    "Holten",
    "Hoofddorp",
    "Hoogeveen",
    "Hoogezand-Sappemeer",
    "Hoogkarspel",
    "Hoorn Kersenboogerd",
    "Hoorn",
    "Horst-Sevenum",
    "Houten Castellum",
    "Houten",
    "Houthem-Sint Gerlach",
    "Hurdegaryp",
    "IJlst",
    "Kampen",
    "Kampen Zuid",
    "Kapelle-Biezelinge",
    "Kerkrade Centrum",
    "Kesteren",
    "Klarenbeek",
    "Klimmen-Ransdaal",
    "Koog aan de Zaan",
    "Koudum-Molkwerum",
    "Krabbendijke",
    "Krommenie-Assendelft",
    "Kropswolde",
    "Kruiningen-Yerseke",
    "Lage Zwaluwe",
    "Landgraaf",
    "Lansingerland-Zoetermeer",
    "Leerdam",
    "Leeuwarden Camminghaburen",
    "Leeuwarden",
    "Leiden Centraal",
    "Leiden Lammenschans",
    "Lelystad Centrum",
    "Lichtenvoorde-Groenlo",
    "Lochem",
    "Loppersum",
    "Lunteren",
    "Maarheeze",
    "Maarn",
    "Maarssen",
    "Maastricht Noord",
    "Maastricht",
    "Maastricht Randwyck",
    "Mantgum",
    "Mariënberg",
    "Martenshoek",
    "Meerssen",
    "Meppel",
    "Middelburg",
    "Mook-Molenhoek",
    "Naarden-Bussum",
    "Nieuw Amsterdam",
    "Nieuwerkerk aan den IJssel",
    "Nieuw-Vennep",
    "Nijkerk",
    "Nijmegen Dukenburg",
    "Nijmegen Goffert",
    "Nijmegen Heyendaal",
    "Nijmegen Lent",
    "Nijmegen",
    "Nijverdal",
    "Nunspeet",
    "Nuth",
    "Obdam",
    "Oisterwijk",
    "Oldenzaal",
    "Olst",
    "Ommen",
    "Oosterbeek",
    "Opheusden",
    "Oss",
    "Oss West",
    "Oudenbosch",
    "Overveen",
    "Purmerend Overwhere",
    "Purmerend",
    "Purmerend Weidevenne",
    "Putten",
    "Raalte",
    "Ravenstein",
    "Reuver",
    "Rheden",
    "Rhenen",
    "Rijssen",
    "Rijswijk",
    "Rilland-Bath",
    "Roermond",
    "Roodeschool",
    "Roosendaal",
    "Rosmalen",
    "Rotterdam Alexander",
    "Rotterdam Blaak",
    "Rotterdam Centraal",
    "Rotterdam Lombardijen",
    "Rotterdam Noord",
    "Rotterdam Stadion",
    "Rotterdam Zuid",
    "Ruurlo",
    "Santpoort Noord",
    "Santpoort Zuid",
    "Sassenheim",
    "Sauwerd",
    "Schagen",
    "Scheemda",
    "Schiedam Centrum",
    "Schin op Geul",
    "Schinnen",
    "Schiphol",
    "'s-Hertogenbosch Oost",
    "'s-Hertogenbosch",
    "Sittard",
    "Sliedrecht Baanhoek",
    "Sliedrecht",
    "Sneek Noord",
    "Sneek",
    "Soest (Netherlands)",
    "Soest Zuid",
    "Soestdijk",
    "Spaubeek",
    "Stavoren",
    "Stedum",
    "Steenwijk",
    "Susteren",
    "Swalmen",
    "'t Harde",
    "Tegelen",
    "Terborg",
    "Tiel Passewaaij",
    "Tiel",
    "Tilburg",
    "Tilburg Reeshof",
    "Tilburg Universiteit",
    "Twello",
    "Uitgeest",
    "Uithuizen",
    "Uithuizermeeden",
    "Usquert",
    "Utrecht Centraal",
    "Utrecht Leidsche Rijn",
    "Utrecht Lunetten",
    "Utrecht Maliebaan",
    "Utrecht Overvecht",
    "Utrecht Terwijde",
    "Utrecht Vaartsche Rijn",
    "Utrecht Zuilen",
    "Valkenburg",
    "Varsseveld",
    "Veendam",
    "Veenendaal Centrum",
    "Veenendaal West",
    "Veenendaal-De Klomp",
    "Velp",
    "Venlo",
    "Venray",
    "Vierlingsbeek",
    "Vleuten",
    "Vlissingen",
    "Vlissingen Souburg",
    "Voerendaal",
    "Voorburg",
    "Voorhout",
    "Voorschoten",
    "Voorst-Empe",
    "Vorden",
    "Vriezenveen",
    "Vroomshoop",
    "Vught",
    "Waddinxveen Noord",
    "Waddinxveen",
    "Waddinxveen Triangel",
    "Warffum",
    "Weert",
    "Weesp",
    "Wehl",
    "Westervoort",
    "Wezep",
    "Wierden",
    "Wijchen",
    "Wijhe",
    "Winschoten",
    "Winsum",
    "Winterswijk",
    "Winterswijk West",
    "Woerden",
    "Wolfheze",
    "Wolvega",
    "Workum",
    "Wormerveer",
    "Zaandam Kogerveld",
    "Zaandam",
    "Zaandijk Zaanse Schans",
    "Zaltbommel",
    "Zandvoort aan Zee",
    "Zetten-Andelst",
    "Zevenaar",
    "Zevenbergen",
    "Zoetermeer Oost",
    "Zoetermeer",
    "Zuidbroek",
    "Zuidhorn",
    "Zutphen",
    "Zwijndrecht",
    "Zwolle",
    "Zwolle Stadshagen",
];

pub const ALL_GVB_STATIONS: [&str; 543] = [
    "1e C. Huygensstraat",
    "2e Van der Helststraat",
    "A. Vivaldistraat",
    "A.J. Ernststraat",
    "AZUA",
    "Aalbersestraat",
    "Aalsmeerplein",
    "Abberdaan",
    "Abcoudermeer",
    "Adam Smithplein",
    "Admiraal Helfrichstraat",
    "Admiraal de Ruijterweg",
    "Albert Cuypstraat",
    "Aletta Jacobslaan",
    "Alexanderplein",
    "Allenstraat",
    "Amerbos",
    "Amsteldijk",
    "Amstelkade",
    "Amstelpark",
    "Amstelstation",
    "Amstelveenseweg",
    "Amstelveenseweg TIJDELIJK",
    "Amsterdamse Bos",
    "Ananasplein",
    "Anderlechtlaan",
    "Annie Romeinplein",
    "Anton de Komplein",
    "Antony Moddermanstraat",
    "Antwerpenbaan",
    "Apollolaan",
    "Appelweg",
    "Archimedesweg",
    "Artis/Holocaustmuseum",
    "Assendelftstraat",
    "Atatürk",
    "Azartplein",
    "Backershagen",
    "Baden Powellweg",
    "Bakkerswaal",
    "Banne Buikslootlaan",
    "Barbara Strozzilaan",
    "Barentszplein",
    "Barkpad",
    "Basisweg",
    "Beemsterstraat",
    "Beethovenstraat",
    "Belgiëplein",
    "Benjamin Brittenstraat",
    "Beukenplein",
    "Beukenweg",
    "Bijlmerplein",
    "Bilderdijkstraat",
    "Bloemgracht",
    "Bob Haarmslaan",
    "Bolestein",
    "Bolstoen",
    "Borneolaan",
    "Bornhout",
    "Bos en Lommerplein",
    "Bos en Lommerweg",
    "Bouvigne",
    "BovenIJ ziekenhuis",
    "Bovenkruier",
    "Brinkstraat",
    "Brusselsingel",
    "Buikslotermeerplein",
    "Buiksloterweg",
    "Buiksloterwegveer",
    "Buiten Brouwersstraat",
    "Buiten Oranjestraat",
    "Buiteneilandlaan",
    "Bullepad",
    "Bullewijk",
    "Burg. De Vlugtlaan",
    "Burg. Fockstraat",
    "Burg. Rendorpstraat",
    "Burg. Van Leeuwenlaan",
    "Burg. Van de Pollstraat",
    "Burgemeester Eliasstraat",
    "Burgemeester Fockstraat",
    "Burgemeester Röellstraat",
    "Busstation Elandsgracht",
    "C. van Eesterenlaan",
    "C.K. Eloutstraat",
    "Camperstraat",
    "Carolina MacGillavrylaan",
    "Ceintuurbaan",
    "Centraal Station",
    "Centrum Nieuw Sloten",
    "Centrumeiland",
    "Ch. de Bourbonstraat",
    "Concertgebouw",
    "Contactweg",
    "Corantijnstraat",
    "Cornelis Lelylaan",
    "Cornelis Schuytstraat",
    "Daguerrestraat",
    "Dalsteindreef",
    "Dam",
    "Daniel Goedkoopstraat",
    "Dapperstraat",
    "De Boelelaan",
    "De Boelelaan/VU",
    "De Clercqstraat",
    "De Egmondenstraat",
    "De Pijp",
    "De Rijpgracht",
    "De Rijpstraat",
    "De Savornin Lohmanstraat",
    "De Wittenkade",
    "Delflandlaan",
    "Dennenrode",
    "Derkinderenstraat",
    "Diemerparklaan",
    "Dijkgraafplein",
    "Dijkmanshuizenstraat",
    "Dintelstraat",
    "Distelweg",
    "Ditlaar",
    "Dolingadreef",
    "Domenico Scarlattilaan",
    "Dortmuiden",
    "Dostojevskisingel",
    "Dr. H. Colijnstraat",
    "Drentepark",
    "Druivenstraat",
    "Echtenstein",
    "Ecuplein",
    "Eekholt",
    "Eerste Coehoornstraat",
    "Eerste Leeghwaterstraat",
    "Eerste Van Swindenstraat",
    "Egelenburg",
    "Egidiusstraat",
    "Elandsgracht",
    "Elandsgracht [tijdelijk]",
    "Emmastraat",
    "Erasmusgracht",
    "Europaboulevard",
    "Europaplein",
    "Fizeaustraat",
    "Flevopark",
    "Floraweg",
    "Florijn",
    "Fluitschipstraat",
    "Foppingadreef",
    "Frederik Hendrikplnts",
    "Frederiksplein",
    "G.J. Scheurleerweg",
    "G.v. Ledenberchstraat",
    "Gaasp",
    "Gaasperplas",
    "Ganzenhoef",
    "Gebouw Atlas",
    "Geerdinkhof",
    "Gein",
    "Geinbrug",
    "Gelderlandplein NO",
    "Gelderlandplein Noord",
    "Gelderlandplein Oost",
    "Geldershoofd",
    "George Gershwinlaan",
    "Gerrit van der Veenstr",
    "Gijsbrecht v Aemstelpark",
    "Gillis van Ledenberchstr",
    "Gooioord",
    "Grasweg",
    "Griendstraat",
    "Grootzeil",
    "Grubbehoeve",
    "Gustav Mahlerplein",
    "Haardstee",
    "Haarlemmermeerstation",
    "Haarlemmermeerstraat",
    "Haarlemmerplein",
    "Hagedoornplein",
    "Hakfort",
    "Hamerstraat",
    "Haparandaweg",
    "Havikslaan",
    "Heemstedestraat",
    "Hempontplein",
    "Hemsterhuisstraat",
    "Henk Sneevlietweg",
    "Herman Bonpad",
    "Herwijk",
    "Het Breed",
    "Het Funen",
    "Hilversumstraat",
    "Hoekenes",
    "Hogevecht",
    "Hogeweg",
    "Hogewerf",
    "Holendrechtplein",
    "Holterbergweg",
    "Hoofddorpplein",
    "Hoofdweg",
    "Hoogoorddreef/Atlas",
    "Hoogte Kadijk",
    "Hornhaven",
    "Houtmankade",
    "Hugo de Grootplein",
    "Hugo de Vrieslaan",
    "Huigenbos",
    "IBM",
    "IJburg",
    "IJplein",
    "IJsbaanpad",
    "IJtunnel",
    "Ilperveldstraat",
    "Inaristraat",
    "Insulindeweg",
    "Isolatorweg",
    "J. Drijverweg",
    "J.M. den Uylstraat",
    "Jacob Cabeliaustraat",
    "Jacques Veltmanstraat",
    "James Wattstraat",
    "Jan Evertsenstraat",
    "Jan Pieter Heijestraat",
    "Jan Rebelstraat",
    "Jan Schaeferbrug",
    "Jan Tooropstraat",
    "Jan Voermanstraat",
    "Jan van Galenstraat",
    "Jarmuiden",
    "Javaplein",
    "Johan Huizingalaan",
    "Johan van Hasseltweg",
    "John M. Keynesplein",
    "Justus Lipsiusstraat",
    "KNSM-laan",
    "Kaapstadweg",
    "Kabelweg",
    "Kadijksplein",
    "Kadoelenpad",
    "Kalfjeslaan",
    "Kapoeasweg",
    "Karel Doormanstraat",
    "Karspeldreef",
    "Kastelenstraat",
    "Kastrupstraat",
    "Kattenburg",
    "Kattenburgerplein",
    "Kattenburgerstraat",
    "Keerkringpark",
    "Keizersgracht",
    "Kelbergen",
    "Kikkenstein",
    "Kinkerstraat",
    "Klaprozenweg",
    "Koenenkade",
    "Koivistokade",
    "Kometensingel",
    "Koningsplein",
    "Koornhorst",
    "Koos Vorrinkweg",
    "Korte 's-Gravesandestr",
    "Kostverlorenstraat",
    "Kraaiennest",
    "Kraaienneststation",
    "Krugerplein",
    "Kruislaan",
    "La Guardiaweg",
    "La Meye",
    "Laan van Vlaanderen",
    "Laarderhoogtweg",
    "Lambertus Zijlplein",
    "Lange Vonder",
    "Langsom",
    "Leerdamhof",
    "Leidseplein",
    "Leusdenhof",
    "Levantplein",
    "Liergouw",
    "Linnaeusparkweg",
    "Linnaeusstraat",
    "Lorentzlaan",
    "Louis Bouwmeesterstraat",
    "Louis Davidsstraat",
    "Louweshoek",
    "Louwesweg",
    "Lumierestraat",
    "Lumièrestraat",
    "Lutmastraat",
    "Maanstraat",
    "Maasdrielhof",
    "Maassluisstraat",
    "Maasstraat",
    "Majanggracht",
    "Maltaweg",
    "Marco Polostraat",
    "Marie Heinekenplein",
    "Markthallen",
    "Marnixplein",
    "Marnixstraat",
    "Masthof",
    "Matterhorn",
    "Maxwellstraat",
    "Meer en Vaart",
    "Meernhof",
    "Meibergdreef",
    "Meidoornplein",
    "Mercatorplein",
    "Merelstraat",
    "Metaalbewerkerweg",
    "Meteorensingel",
    "Meteorenweg",
    "Michel de Klerkhof",
    "Middenweg",
    "Minervaplein",
    "Molenaarsweg",
    "Molenwerf",
    "Molenwijk",
    "Molukkenstraat",
    "Mosplein",
    "Mr. Visserplein",
    "Muiderpoortstation",
    "Muntplein",
    "Museumplein",
    "NDSM-werf",
    "Naaldwijkstraat",
    "Nachtwachtlaan",
    "Nageljongenstraat",
    "Naritaweg",
    "Nassaukade",
    "Nassauplein",
    "Nelson Mandelapark",
    "Nicolaas Beetsstraat",
    "Nieuw Herlaer",
    "Nieuwe Purmerweg",
    "Nieuwe Willemsstraat",
    "Nieuwerhoek",
    "Nieuwezijds Kolk",
    "Nieuwmarkt",
    "Nolensstraat",
    "Noord",
    "Noorderpark",
    "Noordhollandstraat",
    "Oceaangroep",
    "Oderweg",
    "Olof Palmeplein",
    "Olympiaplein",
    "Olympiaweg",
    "Olympisch Stadion",
    "Ookmeerweg",
    "Oostelijke Handelskade",
    "Oostenburgergracht",
    "Oosterlengte",
    "Oostpoort",
    "Oostzanerdijk",
    "Oranje Nassaulaan",
    "Osdorper Ban",
    "Osdorperweg",
    "Osdorpplein Noord",
    "Osdorpplein Oost",
    "Osdorpplein West",
    "Ottho Heldringstraat",
    "Oudenaardeplantsoen",
    "Overamstel",
    "Overtoom",
    "Overtoomsesluis",
    "Paasheuvelweg",
    "Paleisstraat",
    "Parnassusweg",
    "Pekelharingstraat",
    "Peter Martensstraat",
    "Petmolen",
    "Piet Heinkade",
    "Piet Wiedijkstraat",
    "Pieter A. v Heijningestr",
    "Pieter Oosterhuisstraat",
    "Pilatus",
    "Pinksterbloemstraat",
    "Plantage Lepellaan",
    "Pleimuiden",
    "Plein '40 - '45",
    "Plein '40-45",
    "Plesmanlaan",
    "Plesostraat",
    "Pomonastraat",
    "Pontanusstraat",
    "Pontsteiger",
    "Postjesweg",
    "Presanella",
    "President Kennedylaan",
    "Prins Bernhardplein",
    "Prins Hendrikkade",
    "Prinsengracht",
    "Prinses Irenestraat",
    "Purmerplein",
    "Purmerweg",
    "R.J.H. Fortuynplein",
    "Radboud",
    "Radioweg",
    "Reigersbos",
    "Reigersbroeck",
    "Reimerswaalstraat",
    "Rembrandtplein",
    "Rhenenhof",
    "Rhijnvis Feithstraat",
    "Rietlandpark",
    "Rijksmuseum",
    "Robert Fruinlaan",
    "Rode Kruisstraat",
    "Roelof Hartplein",
    "Rokin",
    "Rozengracht",
    "Rudolf Nurejevstraat",
    "Ruigoord Dorp",
    "Ruysdaelkade",
    "Saaftingestraat",
    "Sam van Houtenstraat",
    "Schaarsbergenstraat",
    "Scharenburg",
    "Scheldestraat",
    "Scherpenzeelstraat",
    "Schoonhovendreef",
    "Science Park",
    "Science Park Aer",
    "Science Park Aqua",
    "Science Park Terra",
    "Seineweg",
    "Siciliëweg",
    "Sierplein",
    "Slijperweg",
    "Slotermeerlaan",
    "Sloterpark",
    "Sloterweg",
    "Sneeuwbalstraat",
    "Soembawastraat",
    "Solebaystraat",
    "Spaarndammerdijk",
    "Spaarndammerstraat",
    "Spaklerweg",
    "Spelderholt",
    "Sporenburg",
    "Sportpark Sloten",
    "Spreeuwenpark",
    "Stadionweg",
    "Staghof",
    "Standerdmolen",
    "Stat. De Vlugtlaan",
    "Statenjachtstraat",
    "Station Bijlmer ArenA",
    "Station Gaasperplas",
    "Station Ganzenhoef",
    "Station Holendrecht",
    "Station Lelylaan",
    "Station Noord",
    "Station RAI",
    "Station Science Park",
    "Station Sloterdijk",
    "Station Zuid",
    "Stationsweg",
    "Staverdenplein",
    "Steigereiland",
    "Stenendokweg",
    "Strandvliet",
    "Surinameplein",
    "Tafelbergweg",
    "Th. Weeversweg",
    "Tjalkstraat",
    "Tosaristraat",
    "Troelstralaan",
    "Tulastraat",
    "Tussendek",
    "VU Medisch Centrum",
    "VU medisch centrum",
    "VUmc Hoofdingang",
    "Valentijnkade",
    "Valeriusplein",
    "Valkenweg",
    "Van Baerlestraat",
    "Van Beuningenplein",
    "Van Boshuizenstraat",
    "Van Hallstraat",
    "Van Heenvlietlaan",
    "Van Heijningestraat",
    "Van Hilligaertstraat",
    "Van Limburg Stirumstraat",
    "Van Mourik Broekmanstr",
    "Van Nijenrodeweg",
    "Van Woustraat",
    "Van der Boechorststraat",
    "Van der Hoopstraat",
    "Van der Madeweg",
    "Veelaan",
    "Veenendaalplein",
    "Vennepluimstraat",
    "Venserpolder",
    "Ventweg",
    "Victorieplein",
    "Vijzelgracht",
    "Volendammerweg",
    "Volkstuin",
    "Voordek",
    "Vorticellaweg",
    "Vredenhof",
    "WC Buikslotermeerplein",
    "Waalstraat",
    "Waddenweg",
    "Wamelstraat",
    "Waterlandplein",
    "Waterlooplein",
    "Weerdestein",
    "Weesperplein",
    "Weltevreden",
    "Wervershoofstraat",
    "Westerdoksdijk",
    "Westermarkt",
    "Westkolkdijk",
    "Westlandgracht",
    "Westmallepad",
    "Westpoortweg",
    "Wibautstraat",
    "Wijttenbachstraat",
    "Willem Gertenbachstraat",
    "Willem Schoutenstraat",
    "Willem de Zwijgerlaan",
    "Willem van Weldammelaan",
    "Willinklaan",
    "Wiltzanghlaan",
    "Witte de Withstraat",
    "Wittenburgergracht",
    "Wolbrantskerkweg",
    "Woudrichemstraat",
    "Zaaiersweg",
    "Zaanstraat",
    "Zamenhofstraat",
    "Zeeburgerdijk",
    "Zeeburgereiland",
    "Zeilstraat",
    "Zoutkeetsgracht",
    "Zuideinde",
    "Zuideinde/Molenaarsweg",
    "Zuideinde/Viaduct",
    "Zuidermolenweg",
    "Zuiderzeeweg",
    "de Entree",
    "muziekgebouw Bimhuis",
    "van Hilligaertstraat",
];
